apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/larswoutersucll/my-app:710b55bbe9e03d5c724919bcd487d1feb78cd7c8
          ports:
            - containerPort: 5000
