apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-app
  template:
    metadata:
      labels:
        app: myapp-app
    spec:
      containers:
        - name: myapp-app
          image: ghcr.io/LarsWoutersUCLL/myapp-app:QA
          ports:
            - containerPort: 5000
