apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/larswoutersucll/my-app:ff208f470224f14f9d1e08b2286203ad71209edd
          ports:
            - containerPort: 5000
